### PR TITLE
Use CMake best practices more consistently

### PR DESCRIPTION
**Pull request by reuk**
- `project` should only be used in CMakeLists that are able to build completely standalone, which is only the case for the top level CMakeLists in this repo
- `cmake_minimum_required` only makes sense in the top level cmakelists
- File globbing (`aux_source_dir`) should be avoided wherever possible
- It's bad practice to manually include inner subfolders of dependencies, unless this has been explicitly allowed by the dependency.

### CODE REVIEW

**Comment by eyalamirmusic** [comment]
@reuk Ah, thank you for those comments!

I have removed all the redundant calls I managed to find.

JUCE will not compile for me without a specific Project and version, and I also think (personally) it's much better to reuse the project name (or some variable) instead of retyping that name, which could change and cause bugs.

As for the JUCE dependencies, I was not accessing any JUCE internals, and only building extras+examples which ATM JUCE isn't offering simple 0-configuration builds for, so even though they 'couple' this project with JUCE internals, it's also the only current way to open JUCE in CLion and build Projucer/DemoRunner/AudioPluginHost without touching build flags. 

I'm happy to remove those once there's a cleaner way to build those as a part of JUCE.

As for globbing: I do understand the reasoning behind not using in real-world projects, but it's also one of the most commonly needed build features when prototyping, or when converting a project from another build system, like the projucer, and I think people should know about it.

I will probably convert some of the example to stop using globbing once I have more examples up.

**Comment by eyalamirmusic** [comment]
I removed all the globbing in the latest commit.

**Comment by reuk** [comment]
> As for the JUCE dependencies, I was not accessing any JUCE internals, and only building extras+examples which ATM JUCE isn't offering simple 0-configuration builds for, so even though they 'couple' this project with JUCE internals, it's also the only current way to open JUCE in CLion and build Projucer/DemoRunner/AudioPluginHost without touching build flags.

JUCE provides options (`JUCE_BUILD_EXTRAS` and `JUCE_BUILD_EXAMPLES`) which can be set before adding the JUCE subdirectory for exactly this purpose. This allows the complete removal of the custom cmakelists for the examples/extras directories.

**Comment by eyalamirmusic** [comment]
Right, so I wanted to show how you can have a Projucer/Audio Plugin Host build as a part of your project without the needs to set up your environment/flags, which is also how I'm setting up my user projects. 

Remember - this repo is not a library, this is an example of how I would set up a company/personal repo, and a requirement for me is to be able to build all the needed tools anywhere without configuring the build environment, learn library flags, etc.

**Comment by reuk** [comment]
Sure, no special environment or command-line flags are required when building this patch. Just `cmake -B build` works.

**Comment by eyalamirmusic** [comment]
Yeah, same for opening in Visual Studio/Clion/VSCode/etc.

I do think having self-contained builds is one of the big features of CMake, not just for easy building for a dev, but also for CI, etc. 

So that was the important side I wanted to show in this repo - I might need to update the docs to clarify that this isn't created as a reusable library. Thank you again for all your help! :)

**Pull request closed without merging**
